/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'countContactForms' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getComponentFeatures' : IDL.Func(
      [],
      [
        IDL.Record({
          'aboutSection' : IDL.Bool,
          'heroSection' : IDL.Bool,
          'businessAreasSection' : IDL.Bool,
          'valuesSection' : IDL.Bool,
          'contactSection' : IDL.Bool,
          'footer' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'getContactForm' : IDL.Func([IDL.Text], [ContactForm], ['query']),
  'getContactFormsByEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ContactForm)],
      ['query'],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'countContactForms' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllContactForms' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getComponentFeatures' : IDL.Func(
        [],
        [
          IDL.Record({
            'aboutSection' : IDL.Bool,
            'heroSection' : IDL.Bool,
            'businessAreasSection' : IDL.Bool,
            'valuesSection' : IDL.Bool,
            'contactSection' : IDL.Bool,
            'footer' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'getContactForm' : IDL.Func([IDL.Text], [ContactForm], ['query']),
    'getContactFormsByEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ContactForm)],
        ['query'],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };